### PR TITLE
Update buntdb_test.go

### PR DESCRIPTION
**Pull request by kayabe**
possible reproduction of #74

### CODE REVIEW

**Comment by kayabe** [comment]
@tidwall would you be able to take a look?

**Comment by tidwall** [comment]
From the [Transactions](https://github.com/tidwall/buntdb#transactions) section in the README.

> Transactions run in a function that exposes a Tx object, which represents the transaction state. While inside a transaction, all database operations should be performed using this object. You should never access the origin DB object while inside a transaction. Doing so may have side-effects, such as blocking your application.


You are accessing the `db` from inside a transaction by nesting one `db.View` inside another `db.View`.

**Comment by kayabe** [comment]
i've used it that way because its the only way to get TTL by key without having access to the previous Transaction,
is it be possible to get TTL without db.View (other than using a reference of the previous transaction)?

P.S. this is the only case in which i got a deadlock

**Comment by tidwall** [comment]
You need to use a transaction to get a TTL. Is there a reason why you can't use the existing Tx?

```go
err := db.View(func(tx *Tx) error {
	tx.Ascend("", func(key, value string) bool {
		_, err := tx.TTL(key)
		if err != nil {
			t.Fatal(err)
		}
		return true
	})
	return nil
})
```

**Comment by kayabe** [comment]
yes, storing the key/value in a separate variable and trying to request TTL after the interation over the table

**Pull request closed without merging**
